server:
  port: 9696
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: rmkr
    password: rmkrstage
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
  application:
    name: TODO-Application
